make steps (`.s`, `.browse` etc.) available on `IterableOnce` also (#3581)
* make steps (`.s`, `.browse` etc.) available on `IterableOnce` also

this fixes the following, since `.sorted` returns a `Seq`:
```
joern> cpg.method.external.fullName.sorted.browse
-- [E008] Not Found Error: -----------------------------------------------------
1 |cpg.method.external.fullName.sorted.browse
  |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |value browse is not a member of Seq[String]
```

* fmt