drop `_root_` prefix, which for some reason leads to a strange error:
```
joern> ***** missing reference, looking for Factory/T in package scala.collection.compat.package
decls = Scope{}
-- [E008] Not Found Error: cmd9999999.sc:69:14 ---------------------------------
69 |import _root_._root_.io.shiftleft.passes.{
   |       ^^^^^^^^^^^^^
   |value _root_ is not a member of <root>, but could be made available as an extension method.

```